server:
  port: ${SERVER.PORT:88}

spring:
  # 环境 dev|test|prod
  profiles:
    active: ${PROFILES.ACTIVE:dev}

  # 网关控制
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        ## 一个请求满足多个路由的谓词条件时，请求只会被首个成功匹配的路由转发
        - id: mall-third-party
          uri: lb://mall-third-party
          predicates:
            - Path=/api/mall-third-party/**
          filters:
            - StripPrefix=1

        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/api/mall-admin/**
          filters:
            - StripPrefix=1

        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/api/mall-auth/**
          filters:
            - StripPrefix=1

        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/api/mall-product/**
          filters:
            - StripPrefix=1

        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/api/mall-member/**
          filters:
            - StripPrefix=1

        - id: mall-ware
          uri: lb://mall-ware
          predicates:
            - Path=/api/mall-ware/**
          filters:
            - StripPrefix=1

        - id: mall-cart
          uri: lb://mall-cart
          predicates:
            - Path=/api/mall-cart/**
          filters:
            - StripPrefix=1

        - id: mall-coupon
          uri: lb://mall-coupon
          predicates:
            - Path=/api/mall-coupon/**
          filters:
            - StripPrefix=1

        - id: mall-seckill
          uri: lb://mall-seckill
          predicates:
            - Path=/api/mall-seckill/**
          filters:
            - StripPrefix=1

        # springdoc openapi 路由规则转发
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/$\{path}/v3/api-docs