server:
  port: ${SERVER.PORT:88}

spring:
  # 环境 dev|test|prod
  profiles:
    active: ${PROFILES.ACTIVE:dev}

  # 网关控制
  cloud:
    gateway:
      routes:
        ## 一个请求满足多个路由的谓词条件时，请求只会被首个成功匹配的路由转发
        - id: gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/gulimall-third-party/**
          filters:
            - StripPrefix=1

        - id: gulimall-admin
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/gulimall-admin/**
          filters:
            - StripPrefix=1

        - id: gulimall-auth
          uri: lb://gulimall-auth
          predicates:
            - Path=/api/gulimall-auth/**
          filters:
            - StripPrefix=1

        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/gulimall-product/**
          filters:
            - StripPrefix=1

        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/gulimall-member/**
          filters:
            - StripPrefix=1

        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/gulimall-ware/**
          filters:
            - StripPrefix=1

        - id: gulimall-cart
          uri: lb://gulimall-cart
          predicates:
            - Path=/api/gulimall-cart/**
          filters:
            - StripPrefix=1

        - id: gulimall-coupon
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/gulimall-coupon/**
          filters:
            - StripPrefix=1

        - id: gulimall-seckill
          uri: lb://gulimall-seckill
          predicates:
            - Path=/api/gulimall-seckill/**
          filters:
            - StripPrefix=1

        - id: gulimall-product-web
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall-search-web
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimall-auth-web
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com

        - id: gulimall-cart-web
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimall-order-web
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimall-seckill-web
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com