server:
  port: 8081
  servlet:
    context-path: /mall-coupon

spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  cloud:
    alibaba:
      seata:
        tx-service-group: mall-coupon-fescar-service-group

# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.flipped.mall.coupon.entity

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always