server:
  port: ${SERVER.PORT:199}
  servlet:
    context-path: /mall-auth

spring:
  profiles:
    active: ${PROFILES.ACTIVE:dev}

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
