# Tomcat
server:
  port: ${SERVER.PORT:9090}
  servlet:
    context-path: /mall-admin

spring:
  # 环境 dev|test|prod
  profiles:
    active: ${PROFILES.ACTIVE:dev}

  main:
    allow-bean-definition-overriding: true

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/admin/*.xml
  type-aliases-package: com.flipped.mall.admin.entity

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always