server:
  port: 8086
  servlet:
    context-path: /mall-cart

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
