server:
  port: 8087
  servlet:
    context-path: /gulimall-seckill

spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  task:
    execution:
      pool:
        core-size: 20
        max-size: 200

