server:
  port: 8087
  servlet:
    context-path: /mall-seckill

spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  task:
    execution:
      pool:
        core-size: 20
        max-size: 200

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always