# Tomcat
server:
  port: 9090
  servlet:
    context-path: /gulimall-admin

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/admin/*.xml
  type-aliases-package: com.laughingather.gulimall.admin.entity