spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gulimall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  # 打印sql
  jpa:
    show-sql: true
    open-in-view: false

logging:
  level:
    root: info
    com:
      laughingather:
        gulimall:
          adminnew:
            mapper: debug
          common:
            aspect: debug

springfox:
  documentation:
    swagger-ui:
      enabled: true