server:
  port: 100
  servlet:
    context-path: /mall-search

spring:
  profiles:
    active: dev

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always