# Tomcat
server:
  port: 8080
  servlet:
    context-path: /gulimall-admin-new

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.laughingather.gulimall.adminnew.entity