# Tomcat
server:
  port: 8080
  servlet:
    context-path: /gulimall-admin-new

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/adminnew/*.xml
  type-aliases-package: com.laughingather.gulimall.adminnew.entity