server:
  port: 88

spring:
  profiles:
    active: dev

  cloud:
    gateway:
      routes:
        ## 一个请求满足多个路由的谓词条件时，请求只会被首个成功匹配的路由转发
        - id: gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/gulimall-third-party/**
          filters:
            - StripPrefix=1

        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/gulimall-product/**
          filters:
            - StripPrefix=1

        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/gulimall-member/**
          filters:
            - StripPrefix=1

        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/gulimall-ware/**
          filters:
            - StripPrefix=1

        - id: gulimall-admin
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /gulimall-admin/$\{segment}

