server:
  port: 88

spring:
  profiles:
    active: dev

  cloud:
    gateway:
      routes:
        - id: gulimall-admin
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /gulimall-admin/$\{segment}

#        - id: gulimall-produce
#          uri: lb://gulimall-produce
#          predicates:
#            - Path=/api/gulimall-produce/**
#          filters:
#            - StripPrefix=1