server:
  port: 8085
  servlet:
    context-path: /gulimall-ware

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root

  cloud:
    alibaba:
      seata:
        tx-service-group: gulimall-ware-fescar-service-group

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.laughingather.gulimall.ware.entity