server:
  port: 8083
  servlet:
    context-path: /mall-order

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root

  session:
    store-type: redis

  rabbitmq:
    # 确认消息已发送到交换机
    publisher-confirm-type: correlated
    # 确认消息已发送到队列
    publisher-returns: true
    # 只要发送到队列，以异步方式优先回调returns
    template:
      mandatory: true
    # 消费端确认消息类型  manual是手动确认模式
    listener:
      simple:
        acknowledge-mode: manual

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.flipped.mall.order.entity